version: "3"
services:
  db:
   image: postgres
   restart: always
   ports:
     - "5433:5433"
   environment:
     POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
